//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp.ProductoService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProductoContract", Namespace="http://schemas.datacontract.org/2004/07/EntityServices")]
    [System.SerializableAttribute()]
    public partial class ProductoContract : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CantidadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaCompraField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal MedidaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal PCompraField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal PVentaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProveedorField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Cantidad {
            get {
                return this.CantidadField;
            }
            set {
                if ((this.CantidadField.Equals(value) != true)) {
                    this.CantidadField = value;
                    this.RaisePropertyChanged("Cantidad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((this.CodigoField.Equals(value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaCompra {
            get {
                return this.FechaCompraField;
            }
            set {
                if ((this.FechaCompraField.Equals(value) != true)) {
                    this.FechaCompraField = value;
                    this.RaisePropertyChanged("FechaCompra");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Medida {
            get {
                return this.MedidaField;
            }
            set {
                if ((this.MedidaField.Equals(value) != true)) {
                    this.MedidaField = value;
                    this.RaisePropertyChanged("Medida");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal PCompra {
            get {
                return this.PCompraField;
            }
            set {
                if ((this.PCompraField.Equals(value) != true)) {
                    this.PCompraField = value;
                    this.RaisePropertyChanged("PCompra");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal PVenta {
            get {
                return this.PVentaField;
            }
            set {
                if ((this.PVentaField.Equals(value) != true)) {
                    this.PVentaField = value;
                    this.RaisePropertyChanged("PVenta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Proveedor {
            get {
                return this.ProveedorField;
            }
            set {
                if ((object.ReferenceEquals(this.ProveedorField, value) != true)) {
                    this.ProveedorField = value;
                    this.RaisePropertyChanged("Proveedor");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProductoService.IProductoWS")]
    public interface IProductoWS {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductoWS/ObtenerProducto", ReplyAction="http://tempuri.org/IProductoWS/ObtenerProductoResponse")]
        WebApp.ProductoService.ProductoContract ObtenerProducto(int codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductoWS/ObtenerProducto", ReplyAction="http://tempuri.org/IProductoWS/ObtenerProductoResponse")]
        System.Threading.Tasks.Task<WebApp.ProductoService.ProductoContract> ObtenerProductoAsync(int codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductoWS/GuardarProducto", ReplyAction="http://tempuri.org/IProductoWS/GuardarProductoResponse")]
        int GuardarProducto(WebApp.ProductoService.ProductoContract cliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductoWS/GuardarProducto", ReplyAction="http://tempuri.org/IProductoWS/GuardarProductoResponse")]
        System.Threading.Tasks.Task<int> GuardarProductoAsync(WebApp.ProductoService.ProductoContract cliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductoWS/ModificarProducto", ReplyAction="http://tempuri.org/IProductoWS/ModificarProductoResponse")]
        int ModificarProducto(WebApp.ProductoService.ProductoContract cliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductoWS/ModificarProducto", ReplyAction="http://tempuri.org/IProductoWS/ModificarProductoResponse")]
        System.Threading.Tasks.Task<int> ModificarProductoAsync(WebApp.ProductoService.ProductoContract cliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductoWS/EliminarProducto", ReplyAction="http://tempuri.org/IProductoWS/EliminarProductoResponse")]
        int EliminarProducto(int codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductoWS/EliminarProducto", ReplyAction="http://tempuri.org/IProductoWS/EliminarProductoResponse")]
        System.Threading.Tasks.Task<int> EliminarProductoAsync(int codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductoWS/ListaPagProducto", ReplyAction="http://tempuri.org/IProductoWS/ListaPagProductoResponse")]
        WebApp.ProductoService.ProductoContract[] ListaPagProducto(int pagina);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductoWS/ListaPagProducto", ReplyAction="http://tempuri.org/IProductoWS/ListaPagProductoResponse")]
        System.Threading.Tasks.Task<WebApp.ProductoService.ProductoContract[]> ListaPagProductoAsync(int pagina);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IProductoWSChannel : WebApp.ProductoService.IProductoWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProductoWSClient : System.ServiceModel.ClientBase<WebApp.ProductoService.IProductoWS>, WebApp.ProductoService.IProductoWS {
        
        public ProductoWSClient() {
        }
        
        public ProductoWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProductoWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProductoWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProductoWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WebApp.ProductoService.ProductoContract ObtenerProducto(int codigo) {
            return base.Channel.ObtenerProducto(codigo);
        }
        
        public System.Threading.Tasks.Task<WebApp.ProductoService.ProductoContract> ObtenerProductoAsync(int codigo) {
            return base.Channel.ObtenerProductoAsync(codigo);
        }
        
        public int GuardarProducto(WebApp.ProductoService.ProductoContract cliente) {
            return base.Channel.GuardarProducto(cliente);
        }
        
        public System.Threading.Tasks.Task<int> GuardarProductoAsync(WebApp.ProductoService.ProductoContract cliente) {
            return base.Channel.GuardarProductoAsync(cliente);
        }
        
        public int ModificarProducto(WebApp.ProductoService.ProductoContract cliente) {
            return base.Channel.ModificarProducto(cliente);
        }
        
        public System.Threading.Tasks.Task<int> ModificarProductoAsync(WebApp.ProductoService.ProductoContract cliente) {
            return base.Channel.ModificarProductoAsync(cliente);
        }
        
        public int EliminarProducto(int codigo) {
            return base.Channel.EliminarProducto(codigo);
        }
        
        public System.Threading.Tasks.Task<int> EliminarProductoAsync(int codigo) {
            return base.Channel.EliminarProductoAsync(codigo);
        }
        
        public WebApp.ProductoService.ProductoContract[] ListaPagProducto(int pagina) {
            return base.Channel.ListaPagProducto(pagina);
        }
        
        public System.Threading.Tasks.Task<WebApp.ProductoService.ProductoContract[]> ListaPagProductoAsync(int pagina) {
            return base.Channel.ListaPagProductoAsync(pagina);
        }
    }
}
