//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp.ClienteService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ClienteContract", Namespace="http://schemas.datacontract.org/2004/07/EntityServices")]
    [System.SerializableAttribute()]
    public partial class ClienteContract : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApellidosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DNIField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DireccionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombresField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RazonSocialField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelefonoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TipoClienteField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Apellidos {
            get {
                return this.ApellidosField;
            }
            set {
                if ((object.ReferenceEquals(this.ApellidosField, value) != true)) {
                    this.ApellidosField = value;
                    this.RaisePropertyChanged("Apellidos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((this.CodigoField.Equals(value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DNI {
            get {
                return this.DNIField;
            }
            set {
                if ((object.ReferenceEquals(this.DNIField, value) != true)) {
                    this.DNIField = value;
                    this.RaisePropertyChanged("DNI");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Direccion {
            get {
                return this.DireccionField;
            }
            set {
                if ((object.ReferenceEquals(this.DireccionField, value) != true)) {
                    this.DireccionField = value;
                    this.RaisePropertyChanged("Direccion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombres {
            get {
                return this.NombresField;
            }
            set {
                if ((object.ReferenceEquals(this.NombresField, value) != true)) {
                    this.NombresField = value;
                    this.RaisePropertyChanged("Nombres");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RazonSocial {
            get {
                return this.RazonSocialField;
            }
            set {
                if ((object.ReferenceEquals(this.RazonSocialField, value) != true)) {
                    this.RazonSocialField = value;
                    this.RaisePropertyChanged("RazonSocial");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Telefono {
            get {
                return this.TelefonoField;
            }
            set {
                if ((object.ReferenceEquals(this.TelefonoField, value) != true)) {
                    this.TelefonoField = value;
                    this.RaisePropertyChanged("Telefono");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TipoCliente {
            get {
                return this.TipoClienteField;
            }
            set {
                if ((this.TipoClienteField.Equals(value) != true)) {
                    this.TipoClienteField = value;
                    this.RaisePropertyChanged("TipoCliente");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ClientePagedContract", Namespace="http://schemas.datacontract.org/2004/07/EntityServices")]
    [System.SerializableAttribute()]
    public partial class ClientePagedContract : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebApp.ClienteService.ClienteContract[] RecordsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TotalRecordsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebApp.ClienteService.ClienteContract[] Records {
            get {
                return this.RecordsField;
            }
            set {
                if ((object.ReferenceEquals(this.RecordsField, value) != true)) {
                    this.RecordsField = value;
                    this.RaisePropertyChanged("Records");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalRecords {
            get {
                return this.TotalRecordsField;
            }
            set {
                if ((this.TotalRecordsField.Equals(value) != true)) {
                    this.TotalRecordsField = value;
                    this.RaisePropertyChanged("TotalRecords");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ClienteService.IClienteWS")]
    public interface IClienteWS {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClienteWS/ObtenerCliente", ReplyAction="http://tempuri.org/IClienteWS/ObtenerClienteResponse")]
        WebApp.ClienteService.ClienteContract ObtenerCliente(int codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClienteWS/ObtenerCliente", ReplyAction="http://tempuri.org/IClienteWS/ObtenerClienteResponse")]
        System.Threading.Tasks.Task<WebApp.ClienteService.ClienteContract> ObtenerClienteAsync(int codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClienteWS/GuardarCliente", ReplyAction="http://tempuri.org/IClienteWS/GuardarClienteResponse")]
        int GuardarCliente(WebApp.ClienteService.ClienteContract cliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClienteWS/GuardarCliente", ReplyAction="http://tempuri.org/IClienteWS/GuardarClienteResponse")]
        System.Threading.Tasks.Task<int> GuardarClienteAsync(WebApp.ClienteService.ClienteContract cliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClienteWS/ModificarCliente", ReplyAction="http://tempuri.org/IClienteWS/ModificarClienteResponse")]
        int ModificarCliente(WebApp.ClienteService.ClienteContract cliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClienteWS/ModificarCliente", ReplyAction="http://tempuri.org/IClienteWS/ModificarClienteResponse")]
        System.Threading.Tasks.Task<int> ModificarClienteAsync(WebApp.ClienteService.ClienteContract cliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClienteWS/EliminarCliente", ReplyAction="http://tempuri.org/IClienteWS/EliminarClienteResponse")]
        int EliminarCliente(int codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClienteWS/EliminarCliente", ReplyAction="http://tempuri.org/IClienteWS/EliminarClienteResponse")]
        System.Threading.Tasks.Task<int> EliminarClienteAsync(int codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClienteWS/ListaPagCliente", ReplyAction="http://tempuri.org/IClienteWS/ListaPagClienteResponse")]
        WebApp.ClienteService.ClientePagedContract ListaPagCliente(int pagina);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClienteWS/ListaPagCliente", ReplyAction="http://tempuri.org/IClienteWS/ListaPagClienteResponse")]
        System.Threading.Tasks.Task<WebApp.ClienteService.ClientePagedContract> ListaPagClienteAsync(int pagina);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IClienteWSChannel : WebApp.ClienteService.IClienteWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ClienteWSClient : System.ServiceModel.ClientBase<WebApp.ClienteService.IClienteWS>, WebApp.ClienteService.IClienteWS {
        
        public ClienteWSClient() {
        }
        
        public ClienteWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ClienteWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ClienteWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ClienteWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WebApp.ClienteService.ClienteContract ObtenerCliente(int codigo) {
            return base.Channel.ObtenerCliente(codigo);
        }
        
        public System.Threading.Tasks.Task<WebApp.ClienteService.ClienteContract> ObtenerClienteAsync(int codigo) {
            return base.Channel.ObtenerClienteAsync(codigo);
        }
        
        public int GuardarCliente(WebApp.ClienteService.ClienteContract cliente) {
            return base.Channel.GuardarCliente(cliente);
        }
        
        public System.Threading.Tasks.Task<int> GuardarClienteAsync(WebApp.ClienteService.ClienteContract cliente) {
            return base.Channel.GuardarClienteAsync(cliente);
        }
        
        public int ModificarCliente(WebApp.ClienteService.ClienteContract cliente) {
            return base.Channel.ModificarCliente(cliente);
        }
        
        public System.Threading.Tasks.Task<int> ModificarClienteAsync(WebApp.ClienteService.ClienteContract cliente) {
            return base.Channel.ModificarClienteAsync(cliente);
        }
        
        public int EliminarCliente(int codigo) {
            return base.Channel.EliminarCliente(codigo);
        }
        
        public System.Threading.Tasks.Task<int> EliminarClienteAsync(int codigo) {
            return base.Channel.EliminarClienteAsync(codigo);
        }
        
        public WebApp.ClienteService.ClientePagedContract ListaPagCliente(int pagina) {
            return base.Channel.ListaPagCliente(pagina);
        }
        
        public System.Threading.Tasks.Task<WebApp.ClienteService.ClientePagedContract> ListaPagClienteAsync(int pagina) {
            return base.Channel.ListaPagClienteAsync(pagina);
        }
    }
}
