//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace upc.webapp.PedidoService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PedidoService.IWsPedido")]
    public interface IWsPedido {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWsPedido/Obtener", ReplyAction="http://tempuri.org/IWsPedido/ObtenerResponse")]
        upc.ws.Pedido Obtener(int Codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWsPedido/Obtener", ReplyAction="http://tempuri.org/IWsPedido/ObtenerResponse")]
        System.Threading.Tasks.Task<upc.ws.Pedido> ObtenerAsync(int Codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWsPedido/Registrar", ReplyAction="http://tempuri.org/IWsPedido/RegistrarResponse")]
        int Registrar(upc.ws.Pedido Data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWsPedido/Registrar", ReplyAction="http://tempuri.org/IWsPedido/RegistrarResponse")]
        System.Threading.Tasks.Task<int> RegistrarAsync(upc.ws.Pedido Data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWsPedido/Listar", ReplyAction="http://tempuri.org/IWsPedido/ListarResponse")]
        upc.ws.Pedido[] Listar();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWsPedido/Listar", ReplyAction="http://tempuri.org/IWsPedido/ListarResponse")]
        System.Threading.Tasks.Task<upc.ws.Pedido[]> ListarAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWsPedidoChannel : upc.webapp.PedidoService.IWsPedido, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WsPedidoClient : System.ServiceModel.ClientBase<upc.webapp.PedidoService.IWsPedido>, upc.webapp.PedidoService.IWsPedido {
        
        public WsPedidoClient() {
        }
        
        public WsPedidoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WsPedidoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WsPedidoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WsPedidoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public upc.ws.Pedido Obtener(int Codigo) {
            return base.Channel.Obtener(Codigo);
        }
        
        public System.Threading.Tasks.Task<upc.ws.Pedido> ObtenerAsync(int Codigo) {
            return base.Channel.ObtenerAsync(Codigo);
        }
        
        public int Registrar(upc.ws.Pedido Data) {
            return base.Channel.Registrar(Data);
        }
        
        public System.Threading.Tasks.Task<int> RegistrarAsync(upc.ws.Pedido Data) {
            return base.Channel.RegistrarAsync(Data);
        }
        
        public upc.ws.Pedido[] Listar() {
            return base.Channel.Listar();
        }
        
        public System.Threading.Tasks.Task<upc.ws.Pedido[]> ListarAsync() {
            return base.Channel.ListarAsync();
        }
    }
}
