//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp.PedidoService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Pedido", Namespace="http://schemas.datacontract.org/2004/07/EntityServices")]
    [System.SerializableAttribute()]
    public partial class Pedido : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CodigoClienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebApp.PedidoService.DetallePedido[] DetalleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double IGVField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreClienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double SubTotalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double TotalField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((this.CodigoField.Equals(value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CodigoCliente {
            get {
                return this.CodigoClienteField;
            }
            set {
                if ((this.CodigoClienteField.Equals(value) != true)) {
                    this.CodigoClienteField = value;
                    this.RaisePropertyChanged("CodigoCliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebApp.PedidoService.DetallePedido[] Detalle {
            get {
                return this.DetalleField;
            }
            set {
                if ((object.ReferenceEquals(this.DetalleField, value) != true)) {
                    this.DetalleField = value;
                    this.RaisePropertyChanged("Detalle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Fecha {
            get {
                return this.FechaField;
            }
            set {
                if ((this.FechaField.Equals(value) != true)) {
                    this.FechaField = value;
                    this.RaisePropertyChanged("Fecha");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double IGV {
            get {
                return this.IGVField;
            }
            set {
                if ((this.IGVField.Equals(value) != true)) {
                    this.IGVField = value;
                    this.RaisePropertyChanged("IGV");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreCliente {
            get {
                return this.NombreClienteField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreClienteField, value) != true)) {
                    this.NombreClienteField = value;
                    this.RaisePropertyChanged("NombreCliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double SubTotal {
            get {
                return this.SubTotalField;
            }
            set {
                if ((this.SubTotalField.Equals(value) != true)) {
                    this.SubTotalField = value;
                    this.RaisePropertyChanged("SubTotal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Total {
            get {
                return this.TotalField;
            }
            set {
                if ((this.TotalField.Equals(value) != true)) {
                    this.TotalField = value;
                    this.RaisePropertyChanged("Total");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DetallePedido", Namespace="http://schemas.datacontract.org/2004/07/EntityServices")]
    [System.SerializableAttribute()]
    public partial class DetallePedido : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double CantidadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CodigoProductoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreProductoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PedidoIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double PrecioUField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double SubTotalField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Cantidad {
            get {
                return this.CantidadField;
            }
            set {
                if ((this.CantidadField.Equals(value) != true)) {
                    this.CantidadField = value;
                    this.RaisePropertyChanged("Cantidad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CodigoProducto {
            get {
                return this.CodigoProductoField;
            }
            set {
                if ((this.CodigoProductoField.Equals(value) != true)) {
                    this.CodigoProductoField = value;
                    this.RaisePropertyChanged("CodigoProducto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreProducto {
            get {
                return this.NombreProductoField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreProductoField, value) != true)) {
                    this.NombreProductoField = value;
                    this.RaisePropertyChanged("NombreProducto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PedidoId {
            get {
                return this.PedidoIdField;
            }
            set {
                if ((this.PedidoIdField.Equals(value) != true)) {
                    this.PedidoIdField = value;
                    this.RaisePropertyChanged("PedidoId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double PrecioU {
            get {
                return this.PrecioUField;
            }
            set {
                if ((this.PrecioUField.Equals(value) != true)) {
                    this.PrecioUField = value;
                    this.RaisePropertyChanged("PrecioU");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double SubTotal {
            get {
                return this.SubTotalField;
            }
            set {
                if ((this.SubTotalField.Equals(value) != true)) {
                    this.SubTotalField = value;
                    this.RaisePropertyChanged("SubTotal");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PedidoService.IPedidoService")]
    public interface IPedidoService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPedidoService/Obtener", ReplyAction="http://tempuri.org/IPedidoService/ObtenerResponse")]
        WebApp.PedidoService.Pedido Obtener(int Codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPedidoService/Obtener", ReplyAction="http://tempuri.org/IPedidoService/ObtenerResponse")]
        System.Threading.Tasks.Task<WebApp.PedidoService.Pedido> ObtenerAsync(int Codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPedidoService/Registrar", ReplyAction="http://tempuri.org/IPedidoService/RegistrarResponse")]
        int Registrar(WebApp.PedidoService.Pedido Data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPedidoService/Registrar", ReplyAction="http://tempuri.org/IPedidoService/RegistrarResponse")]
        System.Threading.Tasks.Task<int> RegistrarAsync(WebApp.PedidoService.Pedido Data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPedidoService/Listar", ReplyAction="http://tempuri.org/IPedidoService/ListarResponse")]
        WebApp.PedidoService.Pedido[] Listar();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPedidoService/Listar", ReplyAction="http://tempuri.org/IPedidoService/ListarResponse")]
        System.Threading.Tasks.Task<WebApp.PedidoService.Pedido[]> ListarAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPedidoServiceChannel : WebApp.PedidoService.IPedidoService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PedidoServiceClient : System.ServiceModel.ClientBase<WebApp.PedidoService.IPedidoService>, WebApp.PedidoService.IPedidoService {
        
        public PedidoServiceClient() {
        }
        
        public PedidoServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PedidoServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PedidoServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PedidoServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WebApp.PedidoService.Pedido Obtener(int Codigo) {
            return base.Channel.Obtener(Codigo);
        }
        
        public System.Threading.Tasks.Task<WebApp.PedidoService.Pedido> ObtenerAsync(int Codigo) {
            return base.Channel.ObtenerAsync(Codigo);
        }
        
        public int Registrar(WebApp.PedidoService.Pedido Data) {
            return base.Channel.Registrar(Data);
        }
        
        public System.Threading.Tasks.Task<int> RegistrarAsync(WebApp.PedidoService.Pedido Data) {
            return base.Channel.RegistrarAsync(Data);
        }
        
        public WebApp.PedidoService.Pedido[] Listar() {
            return base.Channel.Listar();
        }
        
        public System.Threading.Tasks.Task<WebApp.PedidoService.Pedido[]> ListarAsync() {
            return base.Channel.ListarAsync();
        }
    }
}
